name: Deploy to Vercel

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: vercel-deploy-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  deployments: write
  id-token: write
  pull-requests: write

cache-mode: none

jobs:
  ylockers-ui-yb:
    uses: yearn/yearn-gha/.github/workflows/vercel-deploy.yml@e6b4d914d9256b6becdf7c30605238894fa54638
    with:
      project: ylockers-ui-yb
      identity-id: ${{ github.event_name == 'pull_request' && vars.DOPPLER_PREVIEW_IDENTITY_ID || vars.DOPPLER_PRODUCTION_IDENTITY_ID }}
  ylockers-ycrv:
    uses: yearn/yearn-gha/.github/workflows/vercel-deploy.yml@e6b4d914d9256b6becdf7c30605238894fa54638
    with:
      project: ylockers-ycrv
      identity-id: ${{ github.event_name == 'pull_request' && vars.DOPPLER_PREVIEW_IDENTITY_ID || vars.DOPPLER_PRODUCTION_IDENTITY_ID }}
  ylockers-yprisma:
    uses: yearn/yearn-gha/.github/workflows/vercel-deploy.yml@e6b4d914d9256b6becdf7c30605238894fa54638
    with:
      project: ylockers-yprisma
      identity-id: ${{ github.event_name == 'pull_request' && vars.DOPPLER_PREVIEW_IDENTITY_ID || vars.DOPPLER_PRODUCTION_IDENTITY_ID }}
